# RuboCop Configuration for AI Toolkit Rails Apps
# Goals: Reduce new-project noise, exclude generated files, maintain code quality
# This template is copied by ai_rails.rb with TargetRubyVersion dynamically set

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3  # Will be replaced by ai_rails.rb
  SuggestExtensions: false
  Exclude:
    - 'db/**/*schema.rb'
    - 'db/**/schema.rb'
    - 'db/migrate/**/*'
    - 'db/seeds.rb'
    - 'docs/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'config/**/*'
    - 'config.ru'
    - 'config/initializers/**/*'

plugins:
  - rubocop-rails
  - rubocop-rspec

# Readability: 120 chars is reasonable for modern displays
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'

# Frozen string literals add overhead without much benefit in Rails 3+
Style/FrozenStringLiteralComment:
  Enabled: false

# Don't require class/module documentation for every file
Style/Documentation:
  Enabled: false

# Allow longer blocks in specs and config
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

# Allow longer examples in RSpec tests (some tests need more setup/assertions)
RSpec/ExampleLength:
  Enabled: false

# Allow multiple expectations in RSpec tests (some tests check multiple related things)
RSpec/MultipleExpectations:
  Enabled: false

# Allow repeated example structure (different test scenarios can have similar setup)
RSpec/RepeatedExample:
  Enabled: false

# Don't enforce I18n for all user-facing text (app-dependent)
Rails/I18nLocaleTexts:
  Enabled: false

# Allow has_* prefix for predicate methods (has_main_file? conflicts with main_file method)
Naming/PredicatePrefix:
  Exclude:
    - 'app/models/printable.rb'
